---
- import_tasks: load_variables.yaml

- import_tasks: prepare_disk.yaml

- name: Launch VM with QEMU
  shell: "{{ qemu_command }} &"
  args:
    chdir: "{{ output_directory }}/{{ image_name }}"
 
- name: Bootstrap VM if necessary
  include: "{{ item }}"
  with_first_found:
    - files:
        - "{{ platform }}/{{ build_version }}/bootstrap.yaml"
      skip: True

- name: Wait for VM SSH
  wait_for:
    port: 8022
    search_regex: SSH

- name: Configure VM
  include: "{{ platform }}/{{ build_version }}/configure.yaml"

- name: Kill QEMU
  shell: killall qemu-system-x86_64

- name: Rename built image to image_name
  shell: "mv {{ output_directory }}/{{ image_name }}/cloned_image {{ output_directory }}/{{ image_name }}/{{ image_name }}.qcow2"

- name: Create QEMU script
  template:
    src: "{{ platform }}/{{ build_version }}/qemu.j2"
    dest: "{{ output_directory }}/{{ image_name }}/run_{{ image_name }}.sh"
    mode: 0775

- name: Create Ansible inventory
  template:
    src: "{{ platform }}/{{ build_version }}/inventory.j2"
    dest: "{{ output_directory }}/{{ image_name }}/inventory"

- import_tasks: build_wrapper_image.yaml
  when: wrapper_linux_image is defined and wrapper_linux_image
