---
- eos_config:
    src: "{{ platform }}/{{ build_version }}/config.j2"
    save_when: always
    authorize: yes
  vars:
    ansible_user: admin
    ansible_ssh_pass: admin
    ansible_port: 8022
    ansible_network_os: eos
    ansible_host_key_checking: false
